### ISSUE TITLE
No Scanner available

### ISSUE THREAD

**Issue by rifalgrp** [yushulx/flutter_twain_scanner#1]
Hi i have VIISAN document scanner pluged in usb,
when  test this plugin and scan there is no list available.
this VIISAN using twain.
Help if any idea

**Comment by yushulx** [comment]
@rifalgrp have you tried [TWAIN sample code](https://github.com/twain/twain-samples)?

**Comment by rifalgrp** [comment]
ya already tried that its not showing also because they use
Software only virtual scanner
but when i tried random free twain scanner its detected from usb
not from this source can u help with that?

**Comment by yushulx** [comment]
@rifalgrp  The plugin project is ported from the TWAIN sample code. If the TWAIN sample code cannot find your scanner, the Flutter plugin will encounter the same issue. Sorry.

**Comment by rifalgrp** [comment]
Sorry after installing CamDS driver now its connected to camera if using sample [TWAIN sample code](https://github.com/twain/twain-samples)
![image](https://github.com/yushulx/flutter_twain_scanner/assets/130553026/8373dcc5-5ee3-4a8e-8e2a-23284de3913e)
![image](https://github.com/yushulx/flutter_twain_scanner/assets/130553026/43c9e163-493c-4381-9606-300a94767ba7)
![image](https://github.com/yushulx/flutter_twain_scanner/assets/130553026/8c478c96-e7d0-4842-badf-f15356876552)

but list showing on flutter only this
![image](https://github.com/yushulx/flutter_twain_scanner/assets/130553026/e93b51da-e758-43bb-a450-744afddce0bf)
 using this plugin

any idea?

**Comment by yushulx** [comment]
@rifalgrp here is the C++ code to get the sources:

```cpp
void TwainApp::getSources()
{
  if(m_DSMState < 3)
  {
    PrintCMDMessage("You need to open the DSM first.\n");
    return;
  }

  // the list should be empty if adding to it.
  assert( true ==  m_DataSources.empty() );

  // get first
  TW_IDENTITY Source;
  memset(&Source, 0, sizeof(TW_IDENTITY));

  TW_UINT16 twrc;

  twrc = _DSM_Entry(
    &m_MyInfo,
    0,
    DG_CONTROL,
    DAT_IDENTITY,
    MSG_GETFIRST,
    (TW_MEMREF) &Source);

  switch (twrc)
  {
  case TWRC_SUCCESS:
    m_DataSources.push_back(Source);
    break;

  case TWRC_FAILURE:
    printError(0, "Failed to get the data source info!");
    break;

  case TWRC_ENDOFLIST:
    return;
    break;
  }

  // get the rest of the sources
  do
  {
    memset(&Source, 0, sizeof(TW_IDENTITY));

    twrc = _DSM_Entry(
      &m_MyInfo,
      0,
      DG_CONTROL,
      DAT_IDENTITY,
      MSG_GETNEXT,
      (TW_MEMREF) &Source);

    switch (twrc)
    {
    case TWRC_SUCCESS:
      m_DataSources.push_back(Source);
      break;

    case TWRC_FAILURE:
      printError(0, "Failed to get the rest of the data source info!");
      return;
      break;

    case TWRC_ENDOFLIST:
      return;
      break;
    }
    
  }
  while (TWRC_SUCCESS == twrc);

  return;
}
```

You can add the following line to print out the source names in the terminal:

```cpp
PrintCMDMessage("Data sources: %s\n", Source.ProductName);
```

<img width="605" alt="image" src="https://github.com/yushulx/flutter_twain_scanner/assets/2202306/50f5085e-5b12-482d-be43-c91194041256">

**Comment by yushulx** [comment]
@rifalgrp you can also try [https://demo.dynamsoft.com/web-twain/](https://demo.dynamsoft.com/web-twain/) to check whether your scanner could be found.

<img width="770" alt="image" src="https://github.com/yushulx/flutter_twain_scanner/assets/2202306/164327cd-142e-4bab-bd74-e2a008a641c2">

**Comment by rifalgrp** [comment]
i fo

> [TWAIN sample code](https://github.com/twain/twain-samples)?

after recheck this sample only work on Twain Sample GUI App 32bit but not work on regular 64 Twain Sample GUI App
so how to work also on plugin using 32bit

**Comment by rifalgrp** [comment]
> @rifalgrp you can also try https://demo.dynamsoft.com/web-twain/ to check whether your scanner could be found.
> 
> <img alt="image" width="770" src="https://user-images.githubusercontent.com/2202306/246420138-164327cd-142e-4bab-bd74-e2a008a641c2.png">

![image](https://github.com/yushulx/flutter_twain_scanner/assets/130553026/daddb07b-bdae-4a9a-8727-4ca86439b608)

also work on the web

**Comment by yushulx** [comment]
@rifalgrp Create a separate 32-bit process that interfaces with the DLL, and have your 64-bit application communicate with this process, possibly via IPC (inter-process communication) mechanisms such as sockets, named pipes, or other similar technologies. 

You can refer to the implementation of Dynamsoft service.

```bash
C:\Windows\SysWOW64\Dynamsoft\DynamsoftServicex64_18
```

![image](https://github.com/yushulx/flutter_twain_scanner/assets/2202306/622991f7-e769-4985-939e-1aa0ab000251)

**Comment by yushulx** [comment]
@rifalgrp If you don't want to waste time, you can try https://github.com/yushulx/web-twain-windows-desktop, which utilizes Flutter web view and Dynamic Web TWAIN API to implement a desktop document scanning app.

**Comment by yushulx** [comment]
@rifalgrp Please try my latest update. The plugin can now invoke **Dynamsoft Service** to support both 32-bit and 64-bit TWAIN.
